///////////////////////////////////////////////////////////
// Date         Developer    Description
// 2021-03-11   Chase H.     Created intial file for ContosoUniversity
// 2021-03-12   Chase H.     Created Course program
// 2021-03-13   Chase H.     Finished Course program
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    //tinfo200:[2021-03-13-1972039-dykstra1] Set up Course class with DataBaseGeneration CourseID, Title, Credits and Enrollments
    public class Course
    {
        //tinfo200:[2021-03-13-1972039-dykstra1] DatabaseGenerated sets the below CourseID to not be generated by the database
        // use real world course ID's
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }

    }
}
